[bar.default]
capsule = true
capsule_groups = [ "sysmonitor" ]
center = [ "submap", "lock_keys", "media" ]
end = [
    "exchange_rates",
    "weather",
    "separator",
    "keyboard_layout",
    "separator",
    "group:g1",
    "separator",
    "network",
    "bluetooth",
    "separator",
    "volume",
    "clock",
    "separator",
    "notifications",
    "tray"
]
margin_edge = 0.0
margin_ends = 0.0
padding = 4
position = "bottom"
radius = 0
scale = 1.0
start = [ "workspaces", "active_window" ]
thickness = 34
widget_spacing = 12

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "ram", "cpu", "sysmon" ]
    opacity = 1.0
    padding = 6.0

[desktop_widgets]
enabled = false

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = false
    lock_before_suspend = true
    timeout = 900

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.3

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1700.0
    cy = 1129.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 256.0
    box_width = 592.0
    cx = 1704.0
    cy = 304.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        clock_style = "digital"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 256.0
    box_width = 592.0
    cx = 1704.0
    cy = 736.0
    output = "DP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = true
        background_color = "surface"
        shadow = false

[notification]
scale = 1.1

[plugins]
enabled = [ "me/exchange_rates", "me/submap" ]

    [[plugins.source]]
    kind = "path"
    location = "/home/kristijan/.config/noctalia/plugins"
    name = "my-dev"

[shell]
clipboard_enabled = false
font_family = "Cascadia Code"
polkit_agent = true
ui_scale = 1.0

    [shell.panel]
    open_near_click_control_center = true

[theme]
community_palette = "One"
source = "community"

[wallpaper]
directory = "/home/kristijan/Pictures/Wallpapers"

    [wallpaper.automation]
    enabled = true
    interval_minutes = 60

[weather]
auto_locate = true

[widget.active_window]
max_length = 400.0

[widget.clock]
capsule = true
capsule_padding = 10.0
format = "{:%H:%M %a}, {:%b %d}"

[widget.cpu]
capsule = true
capsule_group = "sysmonitor"
capsule_padding = 10.0
display = "text"

[widget.exchange_rates]
type = "me/exchange_rates:exchange_rates"

[widget.keyboard_layout]
capsule = true
capsule_padding = 10.0

[widget.lock_keys]
hide_when_off = true

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.ram]
capsule = true
capsule_group = "sysmonitor"
display = "text"

[widget.separator]
type = "spacer"

[widget.submap]
type = "me/submap:submap"

[widget.sysmon]
capsule = true
capsule_group = "sysmonitor"
display = "text"
stat = "disk_pct"

[widget.weather]
capsule = true
capsule_padding = 10.0

[widget.workspaces]
capsule = true
hide_when_empty = true
scale = 1.2
