require('partials.plugins.custom.replace_pair')
require('partials.plugins.custom.search')
require('partials.plugins.custom.simple_f')
require('partials.plugins.custom.ui')
require('partials.plugins.custom.git_history')
