theme = "tokyonight_moon"

[editor]
line-number = "relative"
cursorline = true
completion-timeout = 10

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
left = ["mode", "spacer", "spacer", "version-control", "file-name", "file-modification-indicator"]
right = ["spinner", "spacer", "file-type", "separator", "position", "separator", "spacer", "position-percentage", "spacer", "diagnostics"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"," = { "c" = "toggle_comments"}
C-s = ":w"

[keys.insert]
"C-[" = "normal_mode"
