#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/bspwm/bspwmrc.layout.sh

bspc config border_width         2
bspc config window_gap          8
bspc config top_padding -1
bspc config bottom_padding -4
bspc config left_padding -1
bspc config right_padding -1
bspc config top_monocle_padding -1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#FF0000"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a '*' state=tiled
bspc rule -a Google-chrome desktop='2'
bspc rule -a 'Microsoft Teams - Preview' desktop='2'
bspc rule -a ViberPC desktop='6'
bspc rule -a Dbeaver desktop='5'
bspc rule -a gnome-calculator state=floating
bspc rule -a Yad state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Screenkey manage=off
setxkbmap -layout 'us,rs' -variant ' ,latin' -option 'grp:lctrl_lwin_toggle'
~/.config/bspwm/bspwmrc.local
~/.config/bspwm/autostart.sh
