_G.kris = {}
pcall(require, 'impatient')

require('partials.abbreviations')
require('partials.plugins')
require('partials.treesitter')
require('partials.lsp')
require('partials.completion')
require('partials.settings')
require('partials.colorscheme')
require('partials.statusline')
require('partials.mappings')
require('partials.filetypes')
require('partials.replace_pair')
require('partials.search')
require('partials.vimspector')
require('partials.ui')
require('partials.simple_f')
require('partials.local_nvimrc')
