_G.kris = {}
require'partials/plugins'
require'partials/treesitter'
require'partials/lsp'
require'partials/completion'
require'partials/abbreviations'
require'partials/telescope'
require'partials/settings'
require'partials/colorscheme'
require'partials/statusline'
require'partials/mappings'
require'partials/filetypes'
require'partials/replace_pair'
require'partials/search'
require'partials/vimspector'
require'partials/rg_source'
