lua require'init'
runtime! partials/settings.vim
runtime! partials/colorscheme.vim
runtime! partials/statusline.vim
runtime! partials/filetype/*.vim
runtime! partials/fzf.vim
runtime! partials/mappings.vim
runtime! partials/abbreviations.vim
runtime! partials/search.vim
runtime! partials/replace_pair.vim
