runtime! partials/plugins.vim
runtime! partials/settings.vim
runtime! partials/colorscheme.vim
runtime! partials/statusline.vim
runtime! partials/filetype/*.vim
runtime! partials/fzf.vim
runtime! partials/snippets.vim
runtime! partials/coc.vim
runtime! partials/defx.vim
runtime! partials/mappings.vim
runtime! partials/abbreviations.vim
runtime! partials/peek.vim
runtime! partials/search.vim
