vim.keymap.set('n', '<F5>', '<Plug>VimspectorToggleBreakpoint')
vim.keymap.set('n', '<F6>', '<Plug>VimspectorToggleConditionalBreakpoint')
vim.keymap.set('n', '<F7>', '<Plug>VimspectorAddFunctionBreakpoint')
vim.keymap.set('n', '<F8>', '<Plug>VimspectorRunToCursor')
vim.keymap.set('n', '<F9>', '<Plug>VimspectorContinue')
vim.keymap.set('n', '<Right>', '<Plug>VimspectorStepOver')
vim.keymap.set('n', '<Up>', '<Plug>VimspectorStepOut')
vim.keymap.set('n', '<Down>', '<Plug>VimspectorStepInto')

vim.api.nvim_create_user_command('VimspectorPause', 'vimspector#Pause()', { force = true })
vim.api.nvim_create_user_command('VimspectorStop', 'vimspector#Stop()', { force = true })
