require('partials/filetypes/go')
require('partials/filetypes/python')
require('partials/filetypes/sql')
require('partials/filetypes/git')
require('partials/filetypes/javascript')
require('partials/filetypes/lua')
