vim.cmd [[augroup python]]
  vim.cmd [[autocmd!]]
  vim.cmd [[autocmd FileType python nmap <buffer><silent><Leader>if :ImportName<CR>]]
  vim.cmd [[autocmd FileType python setlocal textwidth=79]]
vim.cmd [[augroup END]]
