set -g mouse on
set -g status off
set -s extended-keys always
bind-key t set-option status

# Change prefix from Ctrl+b to Ctrl+space
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Enable true color and modern cursor shape support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB,usstyle,extkeys"

# Allow tmux to set the cursor shape correctly
set -g cursor-style bar

# Change the repeat window to 1000ms (1 second) instead of the default 500ms
set -g repeat-time 1000

# 1. Select session with prefix + p (opens the interactive session tree)
bind p choose-tree -s

# 2. Rename session with prefix + r (pre-populates the prompt with the current name)
bind r command-prompt -I "#S" "rename-session '%%'"
bind R source-file ~/.tmux.conf

# Copy mode with y
bind y copy-mode

# Auto rename tmux sessions
set-option -g status-interval 5
set-option -g automatic-rename on
# Keeps ONLY the last 20 characters of the path, cutting off the beginning
set-option -g automatic-rename-format '…#{=-20:pane_current_path}'

bind N command-prompt -p "New session name:" "new-session -s '%%'"
bind V split-window -h
bind H split-window -v
bind C-q kill-pane
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind -r [ switch-client -p
bind -r ] switch-client -n

set-option -g set-titles on
set-option -g set-titles-string "#S: #W"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Enable automatic background saving every 15 minutes
set -g @continuum-save-interval '5'

# Automatically restore sessions when tmux server starts
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
